### ISSUE TITLE
isFileReady never resolving

### ISSUE THREAD

**Issue by AashJ** [wulkano/aperture-node#27]
Running into an issue where `isFileReady` is never resolving. When I attempt to remove those lines, I get hit with this error:
```
Error Domain=AVFoundationErrorDomain Code=-11805 "Cannot Record" UserInfo={NSLocalizedRecoverySuggestion=Try recording again., NSLocalizedDescription=Cannot Record, AVErrorRecordingSuccessfullyFinishedKey=false}
    at makeError (/Users/aash/Developer/Personal/test/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/aash/Developer/Personal/test/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:44023) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

I put up a repro here:
https://github.com/AashJ/aperture-cannot-record-error

**Comment by AashJ** [comment]
This is because i didn't give the requisite permissions
